### ISSUE TITLE
Typos in docker compose file

### ISSUE THREAD

**Issue by Towfiqomi** [eclipse-arrowhead/core-java-spring#177]
```
 authorization:
    container_name: authorization
    image: svetlint/authorization:latest
    depends_on:
      - mysql
    volumes:
      - ./core_system_config/authorizaton.properties:/authorization/application.properties
    ports:
      - 8445:8445
```
It says authorizaton.properties instead of authorization.properties.
